
CC=gcc
CFLAGS=-Wall -Wextra 

all: chutesandladders 

chutesandladders: chutesandladders.h chutesandladders.c main.c
	$(CC) chutesandladders.c chutesandladders.h main.c $(CFLAGS) -o chutesandladders
clean:
	rm chutesandladders
